# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-14 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myGallery', '0002_remove_image_capture_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='capture_date',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
