# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-14 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myGallery', '0003_auto_20190314_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='capture_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
